[mypy]
python_version = 3.11
strict = True
warn_unused_ignores = True
warn_redundant_casts = True
warn_unused_configs = True

explicit_package_bases = True
namespace_packages = True
mypy_path = .

exclude = .venv

[mypy-sentence_transformers.*]
ignore_missing_imports = True

[mypy-sentence_transformers]
ignore_missing_imports = True

[mypy-faiss.*]
ignore_missing_imports = True

[mypy-faiss]
ignore_missing_imports = True

[mypy-requests.*]
ignore_missing_imports = True

[mypy-bs4.*]
ignore_missing_imports = True

[mypy-readability.*]
ignore_missing_imports = True

[mypy-pypdf.*]
ignore_missing_imports = True

[mypy-langgraph.*]
ignore_missing_imports = True
